CREATE TABLE IF NOT EXISTS ak_request_jobs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  request_key VARCHAR(255) NOT NULL COMMENT 'Unique request identity',
  function_name VARCHAR(128) NOT NULL COMMENT 'Registered AKShare function name',
  source_group VARCHAR(32) NOT NULL COMMENT 'eastmoney/sina/ths',
  args_json JSON NULL COMMENT 'Positional arguments',
  kwargs_json JSON NULL COMMENT 'Keyword arguments',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/WAITING_PARENT/RUNNING/SUCCESS/FAILED/CANCELLED',
  attempt_count INT NOT NULL DEFAULT 0 COMMENT 'Execution attempts',
  next_run_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Next eligible execution time',
  lease_until DATETIME NULL COMMENT 'Running lease timeout',
  parent_job_id BIGINT NULL COMMENT 'Parent request id',
  root_job_id BIGINT NULL COMMENT 'Workflow root request id',
  workflow_name VARCHAR(128) NULL COMMENT 'Logical workflow name',
  caller_name VARCHAR(64) NULL COMMENT 'Collector or caller label',
  error_category VARCHAR(32) NULL COMMENT 'network/anti_bot/data/unexpected',
  error_message TEXT NULL COMMENT 'Latest error message',
  result_type VARCHAR(32) NULL COMMENT 'dataframe/json/primitive/null',
  result_json LONGTEXT NULL COMMENT 'Serialized result payload',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  started_at DATETIME NULL COMMENT 'Last execution started at',
  finished_at DATETIME NULL COMMENT 'Last execution finished at',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_request_key (request_key),
  KEY idx_source_status_next (source_group, status, next_run_at),
  KEY idx_parent_status (parent_job_id, status),
  KEY idx_root_job (root_job_id),
  KEY idx_finished_at (finished_at)
) COMMENT='Persistent AKShare request queue for standalone scheduler service';
