CREATE TABLE IF NOT EXISTS cffex_member_rankings (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  product_code VARCHAR(8) NOT NULL COMMENT '品种代码，如 IF/IH/IC/IM/TS/TF/T/TL',
  product_name VARCHAR(64) NOT NULL COMMENT '品种名称',
  contract_code VARCHAR(32) NOT NULL COMMENT '合约代码，如 IF2503',
  trade_date DATE NOT NULL COMMENT '交易日',
  rank_no VARCHAR(16) NOT NULL COMMENT '排名序号，兼容合计行',
  volume_rank VARCHAR(16) NULL COMMENT '成交量排名',
  volume_member VARCHAR(64) NULL COMMENT '成交量会员简称',
  volume_value DECIMAL(20, 2) NULL COMMENT '成交量',
  volume_change_value DECIMAL(20, 2) NULL COMMENT '成交量增减',
  long_rank VARCHAR(16) NULL COMMENT '持买单排名',
  long_member VARCHAR(64) NULL COMMENT '持买单会员简称',
  long_open_interest DECIMAL(20, 2) NULL COMMENT '持买单量',
  long_change_value DECIMAL(20, 2) NULL COMMENT '持买单增减',
  short_rank VARCHAR(16) NULL COMMENT '持卖单排名',
  short_member VARCHAR(64) NULL COMMENT '持卖单会员简称',
  short_open_interest DECIMAL(20, 2) NULL COMMENT '持卖单量',
  short_change_value DECIMAL(20, 2) NULL COMMENT '持卖单增减',
  source_url VARCHAR(255) NOT NULL DEFAULT 'http://www.cffex.com.cn/ccpm/' COMMENT '数据来源',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_trade_contract_rank (trade_date, product_code, contract_code, rank_no),
  KEY idx_product_trade_date (product_code, trade_date),
  KEY idx_contract_trade_date (contract_code, trade_date)
) COMMENT='中金所会员成交及持仓排名数据';
