CREATE TABLE IF NOT EXISTS etf_basic_info (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  etf_code VARCHAR(16) NOT NULL COMMENT 'ETF code, e.g. 510300',
  etf_name VARCHAR(128) NULL COMMENT 'ETF name',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_etf_code (etf_code)
) COMMENT='ETF basic info from AKShare fund_etf_spot_em';


CREATE TABLE IF NOT EXISTS etf_daily_data (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  etf_code VARCHAR(16) NOT NULL COMMENT 'ETF code',
  etf_name VARCHAR(128) NULL COMMENT 'ETF name',
  trade_date DATE NOT NULL COMMENT 'Trading date',
  open_price DECIMAL(18, 6) NULL COMMENT 'Open price',
  close_price DECIMAL(18, 6) NULL COMMENT 'Close/latest price',
  high_price DECIMAL(18, 6) NULL COMMENT 'High price',
  low_price DECIMAL(18, 6) NULL COMMENT 'Low price',
  volume DECIMAL(24, 2) NULL COMMENT 'Volume',
  turnover DECIMAL(28, 2) NULL COMMENT 'Turnover',
  amplitude DECIMAL(18, 6) NULL COMMENT 'Amplitude',
  price_change_rate DECIMAL(18, 6) NULL COMMENT 'Change rate',
  price_change_amount DECIMAL(18, 6) NULL COMMENT 'Change amount',
  turnover_rate DECIMAL(18, 6) NULL COMMENT 'Turnover rate',
  pre_close_price DECIMAL(18, 6) NULL COMMENT 'Previous close price',
  iopv_realtime DECIMAL(18, 6) NULL COMMENT 'IOPV realtime estimate',
  discount_rate DECIMAL(18, 6) NULL COMMENT 'ETF discount/premium rate',
  volume_ratio DECIMAL(18, 6) NULL COMMENT 'Volume ratio',
  current_hand DECIMAL(24, 2) NULL COMMENT 'Current hand',
  bid1_price DECIMAL(18, 6) NULL COMMENT 'Bid1 price',
  ask1_price DECIMAL(18, 6) NULL COMMENT 'Ask1 price',
  outer_volume DECIMAL(24, 2) NULL COMMENT 'Outer volume',
  inner_volume DECIMAL(24, 2) NULL COMMENT 'Inner volume',
  latest_share DECIMAL(24, 2) NULL COMMENT 'Latest share',
  circulating_market_value DECIMAL(24, 2) NULL COMMENT 'Circulating market value',
  total_market_value DECIMAL(24, 2) NULL COMMENT 'Total market value',
  main_net_inflow DECIMAL(24, 2) NULL COMMENT 'Main net inflow amount',
  main_net_inflow_ratio DECIMAL(18, 6) NULL COMMENT 'Main net inflow ratio',
  extra_large_net_inflow DECIMAL(24, 2) NULL COMMENT 'Extra large net inflow amount',
  extra_large_net_inflow_ratio DECIMAL(18, 6) NULL COMMENT 'Extra large net inflow ratio',
  large_net_inflow DECIMAL(24, 2) NULL COMMENT 'Large net inflow amount',
  large_net_inflow_ratio DECIMAL(18, 6) NULL COMMENT 'Large net inflow ratio',
  medium_net_inflow DECIMAL(24, 2) NULL COMMENT 'Medium net inflow amount',
  medium_net_inflow_ratio DECIMAL(18, 6) NULL COMMENT 'Medium net inflow ratio',
  small_net_inflow DECIMAL(24, 2) NULL COMMENT 'Small net inflow amount',
  small_net_inflow_ratio DECIMAL(18, 6) NULL COMMENT 'Small net inflow ratio',
  spot_data_date DATE NULL COMMENT 'Spot payload trade date',
  spot_update_time DATETIME NULL COMMENT 'Spot payload update time',
  data_source VARCHAR(32) NOT NULL DEFAULT 'fund_etf_hist_em' COMMENT 'fund_etf_hist_em or fund_etf_spot_em',
  adjust_type VARCHAR(8) NULL COMMENT 'Adjustment type such as qfq',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_etf_trade_date (etf_code, trade_date),
  KEY idx_data_source_trade_date (data_source, trade_date),
  KEY idx_trade_date (trade_date)
) COMMENT='ETF daily data from AKShare fund_etf_spot_em and fund_etf_hist_em';
