CREATE TABLE IF NOT EXISTS option_cffex_spot_data (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  index_type VARCHAR(16) NOT NULL COMMENT 'Index type: SZ50 / HS300 / ZZ1000',
  index_name VARCHAR(32) NULL COMMENT 'Index name',
  product_code VARCHAR(8) NULL COMMENT 'Sina product code: ho / io / mo',
  contract_symbol VARCHAR(32) NOT NULL COMMENT 'Contract month symbol, e.g. ho2503',
  strike_price DECIMAL(12, 4) NOT NULL COMMENT 'Strike price',
  call_option_symbol VARCHAR(64) NOT NULL COMMENT 'Call option identifier',
  call_buy_volume DECIMAL(20, 2) NULL COMMENT 'Call buy volume',
  call_buy_price DECIMAL(18, 6) NULL COMMENT 'Call buy price',
  call_latest_price DECIMAL(18, 6) NULL COMMENT 'Call latest price',
  call_sell_price DECIMAL(18, 6) NULL COMMENT 'Call sell price',
  call_sell_volume DECIMAL(20, 2) NULL COMMENT 'Call sell volume',
  call_open_interest DECIMAL(20, 2) NULL COMMENT 'Call open interest',
  call_change DECIMAL(18, 6) NULL COMMENT 'Call change',
  put_option_symbol VARCHAR(64) NOT NULL COMMENT 'Put option identifier',
  put_buy_volume DECIMAL(20, 2) NULL COMMENT 'Put buy volume',
  put_buy_price DECIMAL(18, 6) NULL COMMENT 'Put buy price',
  put_latest_price DECIMAL(18, 6) NULL COMMENT 'Put latest price',
  put_sell_price DECIMAL(18, 6) NULL COMMENT 'Put sell price',
  put_sell_volume DECIMAL(20, 2) NULL COMMENT 'Put sell volume',
  put_open_interest DECIMAL(20, 2) NULL COMMENT 'Put open interest',
  put_change DECIMAL(18, 6) NULL COMMENT 'Put change',
  data_source VARCHAR(64) NOT NULL DEFAULT 'option_spot_sina' COMMENT 'Data source',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_index_contract_strike (index_type, contract_symbol, strike_price),
  KEY idx_contract_symbol (contract_symbol),
  KEY idx_call_option_symbol (call_option_symbol),
  KEY idx_put_option_symbol (put_option_symbol)
) COMMENT='CFFEX index option spot chain data from Sina';

CREATE TABLE IF NOT EXISTS option_cffex_daily_data (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  index_type VARCHAR(16) NOT NULL COMMENT 'Index type: SZ50 / HS300 / ZZ1000',
  index_name VARCHAR(32) NULL COMMENT 'Index name',
  product_code VARCHAR(8) NULL COMMENT 'Sina product code: ho / io / mo',
  contract_symbol VARCHAR(32) NULL COMMENT 'Contract month symbol',
  option_symbol VARCHAR(64) NOT NULL COMMENT 'Option identifier, e.g. ho2503C2350',
  option_type VARCHAR(8) NULL COMMENT 'CALL / PUT',
  strike_price DECIMAL(12, 4) NULL COMMENT 'Strike price',
  trade_date DATE NOT NULL COMMENT 'Trade date',
  open_price DECIMAL(18, 6) NULL COMMENT 'Open price',
  high_price DECIMAL(18, 6) NULL COMMENT 'High price',
  low_price DECIMAL(18, 6) NULL COMMENT 'Low price',
  close_price DECIMAL(18, 6) NULL COMMENT 'Close price',
  volume DECIMAL(20, 2) NULL COMMENT 'Volume',
  data_source VARCHAR(64) NOT NULL DEFAULT 'option_daily_sina' COMMENT 'Data source',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_option_symbol_trade_date (option_symbol, trade_date),
  KEY idx_index_type_trade_date (index_type, trade_date),
  KEY idx_contract_symbol_trade_date (contract_symbol, trade_date)
) COMMENT='CFFEX index option daily data from Sina';
