CREATE TABLE IF NOT EXISTS option_cffex_rtj_daily_data (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  index_type VARCHAR(16) NOT NULL COMMENT 'Index type: HS300 / ZZ1000 / SZ50',
  index_name VARCHAR(32) NULL COMMENT 'Index name',
  product_prefix VARCHAR(8) NULL COMMENT 'Contract prefix such as IO / MO / HO',
  contract_code VARCHAR(64) NOT NULL COMMENT 'CFFEX option contract code',
  contract_month VARCHAR(16) NULL COMMENT 'Contract month extracted from contract code',
  option_type VARCHAR(8) NULL COMMENT 'CALL / PUT',
  strike_price DECIMAL(18, 6) NULL COMMENT 'Strike price',
  trade_date DATE NOT NULL COMMENT 'Trade date',
  open_price DECIMAL(18, 6) NULL COMMENT 'Open price',
  high_price DECIMAL(18, 6) NULL COMMENT 'High price',
  low_price DECIMAL(18, 6) NULL COMMENT 'Low price',
  close_price DECIMAL(18, 6) NULL COMMENT 'Close price',
  settle_price DECIMAL(18, 6) NULL COMMENT 'Settlement price',
  pre_settle_price DECIMAL(18, 6) NULL COMMENT 'Previous settlement price',
  price_change_close DECIMAL(18, 6) NULL COMMENT 'Price change 1',
  price_change_settle DECIMAL(18, 6) NULL COMMENT 'Price change 2',
  volume DECIMAL(20, 2) NULL COMMENT 'Volume',
  turnover DECIMAL(24, 2) NULL COMMENT 'Turnover',
  open_interest DECIMAL(20, 2) NULL COMMENT 'Open interest',
  open_interest_change DECIMAL(20, 2) NULL COMMENT 'Open interest change',
  data_source VARCHAR(32) NOT NULL DEFAULT 'cffex_rtj' COMMENT 'Data source',
  source_url VARCHAR(255) NOT NULL DEFAULT 'http://www.cffex.com.cn/rtj/' COMMENT 'Source URL',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_contract_code_trade_date (contract_code, trade_date),
  KEY idx_index_type_trade_date (index_type, trade_date),
  KEY idx_trade_date (trade_date),
  KEY idx_contract_code (contract_code)
) COMMENT='CFFEX option daily statistics from rtj page';
