CREATE TABLE IF NOT EXISTS quant_index_dashboard_daily (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  trade_date DATE NOT NULL COMMENT '交易日期',
  index_code VARCHAR(32) NOT NULL COMMENT '指数代码，需与 FIT /stocks/indexes/options 对齐',
  index_name VARCHAR(64) NOT NULL COMMENT '指数名称',
  emotion_value DECIMAL(18, 6) NOT NULL DEFAULT 50 COMMENT '情绪值',
  main_basis DECIMAL(18, 6) NOT NULL DEFAULT 0 COMMENT '主连期现差',
  month_basis DECIMAL(18, 6) NOT NULL DEFAULT 0 COMMENT '当月连续期现差',
  breadth_up_count INT NOT NULL DEFAULT 0 COMMENT '上涨家数',
  breadth_total_count INT NOT NULL DEFAULT 0 COMMENT '有效总家数',
  breadth_up_pct DECIMAL(18, 6) NOT NULL DEFAULT 0 COMMENT '上涨家数百分比',
  option_pc_current_month DECIMAL(18, 6) NULL COMMENT '当月股指期权Put/Call价格比',
  option_pc_current_month_contract_month VARCHAR(16) NULL COMMENT '当月股指期权合约月份',
  option_pc_current_month_special_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '当月Put/Call是否使用特殊点位计算',
  option_pc_current_month_special_note VARCHAR(512) NULL COMMENT '当月Put/Call特殊点位说明',
  option_pc_next_month DECIMAL(18, 6) NULL COMMENT '下月股指期权Put/Call价格比',
  option_pc_next_month_contract_month VARCHAR(16) NULL COMMENT '下月股指期权合约月份',
  option_pc_next_month_special_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '下月Put/Call是否使用特殊点位计算',
  option_pc_next_month_special_note VARCHAR(512) NULL COMMENT '下月Put/Call特殊点位说明',
  option_pc_quarter_1 DECIMAL(18, 6) NULL COMMENT '第一季月股指期权Put/Call价格比',
  option_pc_quarter_1_contract_month VARCHAR(16) NULL COMMENT '第一季月股指期权合约月份',
  option_pc_quarter_1_special_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '季月1 Put/Call是否使用特殊点位计算',
  option_pc_quarter_1_special_note VARCHAR(512) NULL COMMENT '季月1 Put/Call特殊点位说明',
  option_pc_quarter_2 DECIMAL(18, 6) NULL COMMENT '第二季月股指期权Put/Call价格比',
  option_pc_quarter_2_contract_month VARCHAR(16) NULL COMMENT '第二季月股指期权合约月份',
  option_pc_quarter_2_special_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '季月2 Put/Call是否使用特殊点位计算',
  option_pc_quarter_2_special_note VARCHAR(512) NULL COMMENT '季月2 Put/Call特殊点位说明',
  option_volume_pc_ratio DECIMAL(18, 6) NULL COMMENT '股指期权成交量Put/Call比',
  option_turnover_pc_ratio DECIMAL(18, 6) NULL COMMENT '股指期权成交额Put/Call比',
  exchange_option_pc_json JSON NULL COMMENT '沪深交易所期权分产品Put/Call指标',
  option_vix_json JSON NULL COMMENT '按交易所和期权产品独立计算的30日VIX',
  self_sentiment_score DECIMAL(18, 6) NULL COMMENT '自建情绪综合分',
  self_sentiment_core_score DECIMAL(18, 6) NULL COMMENT '自建情绪价格核心分',
  self_sentiment_derivative_score DECIMAL(18, 6) NULL COMMENT '自建情绪衍生品分',
  self_sentiment_components_json JSON NULL COMMENT '自建情绪分项、原始值和算法版本',
  cffex_top20_net_short_delta_5d DECIMAL(18, 6) NULL COMMENT '前20机构股指期货净空单5交易日增量',
  cffex_top20_net_short_delta_7d DECIMAL(18, 6) NULL COMMENT '前20机构股指期货净空单7交易日增量',
  cffex_top20_net_short_delta_14d DECIMAL(18, 6) NULL COMMENT '前20机构股指期货净空单14交易日增量',
  cffex_top20_net_short_delta_20d DECIMAL(18, 6) NULL COMMENT '前20机构股指期货净空单20交易日增量',
  cffex_top20_net_short_delta_30d DECIMAL(18, 6) NULL COMMENT '前20机构股指期货净空单30交易日增量',
  cffex_top20_net_short_delta_60d DECIMAL(18, 6) NULL COMMENT '前20机构股指期货净空单60交易日增量',
  cffex_top20_net_short_delta_120d DECIMAL(18, 6) NULL COMMENT '前20机构股指期货净空单120交易日增量',
  cffex_citic_net_short_delta_5d DECIMAL(18, 6) NULL COMMENT '中信代客股指期货净空单5交易日增量',
  cffex_citic_net_short_delta_7d DECIMAL(18, 6) NULL COMMENT '中信代客股指期货净空单7交易日增量',
  cffex_citic_net_short_delta_14d DECIMAL(18, 6) NULL COMMENT '中信代客股指期货净空单14交易日增量',
  cffex_citic_net_short_delta_20d DECIMAL(18, 6) NULL COMMENT '中信代客股指期货净空单20交易日增量',
  cffex_citic_net_short_delta_30d DECIMAL(18, 6) NULL COMMENT '中信代客股指期货净空单30交易日增量',
  cffex_citic_net_short_delta_60d DECIMAL(18, 6) NULL COMMENT '中信代客股指期货净空单60交易日增量',
  cffex_citic_net_short_delta_120d DECIMAL(18, 6) NULL COMMENT '中信代客股指期货净空单120交易日增量',
  basis_main_delta_5d DECIMAL(18, 6) NULL COMMENT '主连期现差5交易日变化',
  basis_main_delta_7d DECIMAL(18, 6) NULL COMMENT '主连期现差7交易日变化',
  basis_main_delta_14d DECIMAL(18, 6) NULL COMMENT '主连期现差14交易日变化',
  basis_main_delta_20d DECIMAL(18, 6) NULL COMMENT '主连期现差20交易日变化',
  basis_main_delta_30d DECIMAL(18, 6) NULL COMMENT '主连期现差30交易日变化',
  basis_main_delta_60d DECIMAL(18, 6) NULL COMMENT '主连期现差60交易日变化',
  basis_main_delta_120d DECIMAL(18, 6) NULL COMMENT '主连期现差120交易日变化',
  basis_month_delta_5d DECIMAL(18, 6) NULL COMMENT '月连期现差5交易日变化',
  basis_month_delta_7d DECIMAL(18, 6) NULL COMMENT '月连期现差7交易日变化',
  basis_month_delta_14d DECIMAL(18, 6) NULL COMMENT '月连期现差14交易日变化',
  basis_month_delta_20d DECIMAL(18, 6) NULL COMMENT '月连期现差20交易日变化',
  basis_month_delta_30d DECIMAL(18, 6) NULL COMMENT '月连期现差30交易日变化',
  basis_month_delta_60d DECIMAL(18, 6) NULL COMMENT '月连期现差60交易日变化',
  basis_month_delta_120d DECIMAL(18, 6) NULL COMMENT '月连期现差120交易日变化',
  margin_financing_net_buy_sum_5d DECIMAL(30, 2) NULL COMMENT '近5交易日融资净买入累计额，人民币元',
  margin_financing_net_buy_sum_7d DECIMAL(30, 2) NULL COMMENT '近7交易日融资净买入累计额，人民币元',
  margin_financing_net_buy_sum_14d DECIMAL(30, 2) NULL COMMENT '近14交易日融资净买入累计额，人民币元',
  margin_financing_net_buy_sum_20d DECIMAL(30, 2) NULL COMMENT '近20交易日融资净买入累计额，人民币元',
  margin_financing_net_buy_sum_30d DECIMAL(30, 2) NULL COMMENT '近30交易日融资净买入累计额，人民币元',
  margin_financing_net_buy_sum_60d DECIMAL(30, 2) NULL COMMENT '近60交易日融资净买入累计额，人民币元',
  margin_financing_net_buy_sum_120d DECIMAL(30, 2) NULL COMMENT '近120交易日融资净买入累计额，人民币元',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_quant_index_dashboard_daily_code_date (index_code, trade_date),
  KEY idx_quant_index_dashboard_daily_trade_date (trade_date),
  KEY idx_quant_index_dashboard_daily_name_date (index_name, trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='量化指数看板预计算结果表';
