CREATE TABLE IF NOT EXISTS stock_info_all (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  stock_code VARCHAR(16) NOT NULL,
  prefixed_code VARCHAR(16) NOT NULL,
  exchange VARCHAR(16) NULL,
  market_prefix VARCHAR(8) NULL,
  board VARCHAR(64) NULL,
  security_type VARCHAR(32) NULL,
  stock_name VARCHAR(128) NULL,
  security_full_name VARCHAR(255) NULL,
  company_abbr VARCHAR(128) NULL,
  company_full_name VARCHAR(255) NULL,
  list_date DATE NULL,
  industry VARCHAR(128) NULL,
  region VARCHAR(128) NULL,
  total_share_capital DECIMAL(24, 2) NULL,
  circulating_share_capital DECIMAL(24, 2) NULL,
  source_variants_json LONGTEXT NULL,
  raw_records_json LONGTEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_prefixed_code (prefixed_code),
  KEY idx_stock_info_all_stock_code (stock_code)
);

CREATE TABLE IF NOT EXISTS stock_daily_data (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  stock_code VARCHAR(16) NOT NULL,
  prefixed_code VARCHAR(16) NOT NULL,
  stock_name VARCHAR(128) NULL,
  trade_date DATE NOT NULL,
  open_price DECIMAL(18, 4) NULL,
  close_price DECIMAL(18, 4) NULL,
  high_price DECIMAL(18, 4) NULL,
  low_price DECIMAL(18, 4) NULL,
  latest_price DECIMAL(18, 4) NULL,
  pre_close_price DECIMAL(18, 4) NULL,
  buy_price DECIMAL(18, 4) NULL,
  sell_price DECIMAL(18, 4) NULL,
  price_change_amount DECIMAL(18, 4) NULL,
  price_change_rate DECIMAL(18, 4) NULL,
  volume DECIMAL(24, 2) NULL,
  turnover_amount DECIMAL(24, 2) NULL,
  data_source VARCHAR(64) NOT NULL,
  snapshot_time DATETIME NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_stock_daily_prefixed_date (prefixed_code, trade_date),
  KEY idx_stock_daily_code_date (stock_code, trade_date)
);

CREATE TABLE IF NOT EXISTS stock_qfq_daily_data (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  stock_code VARCHAR(16) NOT NULL,
  prefixed_code VARCHAR(16) NOT NULL,
  stock_name VARCHAR(128) NULL,
  trade_date DATE NOT NULL,
  open_price DECIMAL(18, 4) NULL,
  close_price DECIMAL(18, 4) NULL,
  high_price DECIMAL(18, 4) NULL,
  low_price DECIMAL(18, 4) NULL,
  volume DECIMAL(24, 2) NULL,
  turnover_amount DECIMAL(24, 2) NULL,
  outstanding_share DECIMAL(24, 2) NULL,
  turnover_rate DECIMAL(18, 4) NULL,
  data_source VARCHAR(64) NOT NULL,
  request_start_date DATE NULL,
  request_end_date DATE NULL,
  refresh_batch_id VARCHAR(64) NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_stock_qfq_prefixed_date (prefixed_code, trade_date),
  KEY idx_stock_qfq_code_date (stock_code, trade_date),
  KEY idx_stock_qfq_refresh_batch (refresh_batch_id)
);
